FROM golang:1.26-alpine AS build
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 \
    go build -ldflags="-w -s -X main.version=$(date +%Y%m%d)" -o helix-operator ./cmd/operator/

FROM alpine:3.21
RUN apk add --no-cache ca-certificates tzdata
COPY --from=build /app/helix-operator /helix-operator
EXPOSE 8080 8081
ENTRYPOINT ["/helix-operator"]
